### ISSUE TITLE
Json raw_decode error

### ISSUE THREAD

**Issue by claude974** [tghw/rtkml#2]
Hello
Is it the lastest version of roadttripper API : https://roadtrippers.com/api/v2/trips/ ?
Below you can find the log
Traceback (most recent call last):
  File "M:/rtkml.py", line 37, in <module>
    export(args.trip_id, args.no_waypoints, args.no_paths)
  File "M:/rtkml.py", line 12, in export
    data = resp.json()
  File "C:\Users\Claude\AppData\Roaming\Python\Python37\site-packages\requests\models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\Claude\AppData\Local\Programs\Python\Python37-32\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Claude\AppData\Local\Programs\Python\Python37-32\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Claude\AppData\Local\Programs\Python\Python37-32\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
My tripid is 23628113.
Any Idea of the problem ?
Thanks

**Comment by tghw** [comment]
It looks to me like the trip ID is wrong. If you go to https://roadtrippers.com/api/v2/trips/23628113, it's returning a 404 Not Found error. One of my old trips, however, still works: https://roadtrippers.com/api/v2/trips/10187310. I've updated the script to show the error better.

Double check your trip ID and try again.

**Comment by claude974** [comment]
Hello
It's ok, my trip wasn't shared so the api call return fails.
I may have been misled by the json decode error.
With your update, the message is clear now, thanks.
Just a remark : with my configuration, i have to add brakets in the print command :
print ('Error 404\nCould not find trip %s' % id) instead of print 'Error 404\nCould not find trip %s' % id
Thanks again
